{{- define "library.serviceAccount" -}}
{{- if .Values.serviceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "library.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    {{- include "library.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end -}} 