# Default values for library chart ,reference `library/values.yaml.example` configuration

stage: "dev"    # 环境: dev, test, pre, prod 


deployment:
  replicaCount: 2
  hpa:
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
          - type: Percent
            value: 50
            periodSeconds: 60
          - type: Pods
            value: 4
            periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 120
        policies:
          - type: Percent
            value: 30
            periodSeconds: 60
  labels:
    aaa: bb
  podLabels:
    aaa: pp
  containers:
    - name: main
      image:
        repository: "public.ecr.aws/nginx/nginx"
        tag: "latest"
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi


service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
    - port: 443
      targetPort: 443
      name: https
      protocol: TCP


albIngress:
  loadbalancerName: dev-myapp
  groupName: dev-myapp
  scheme: internet-facing
  targetType: ip
  subnets: subnet-0d09f31ef5327fd5a,subnet-0f266e32c0982c1b2
  certificateArn: arn:aws-cn:acm:cn-northwest-1:475810397983:certificate/0bb02679-12fd-470d-a26f-595a6efeb14c
  sslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01
  httpsRedirect: true
  healthcheckPath: /
  successCodes: 200,301,302
  tags: cost=dev

  hosts:
    - host: myapp.vevortesting.com
      paths:
        - path: "/"
          pathType: Prefix
          serviceName: ""   # 自定义服务名称（留空，默认使用projectName
          port: 80
